name: Full DevOps Pipeline

on:
  push:
    branches: 
        -   master

jobs:

  # 1. TESTING STAGE
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies ## needed for node.js
      run: npm install

    - name: Run unit tests  ## To Tests small parts of your code
      run: npm test

    - name: Coverage Test ## to test How much of the code is tested 
      run: npm run coverage

  # 2. SECURITY STAGE
  security:
    runs-on: ubuntu-latest
    needs: test   ## runs only if test passes

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    
    - name: SCA (Snyk) ## Dependency scan for npm vulnerable packages
      run: |
        npm install -g snyk
        snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


    - name: SonarQube Scan  ## Scans code without running it for bugs
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: SonarSource/sonarqube-scan-action@v6  ## hosted on ec2 instance instaed of sonarcloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # - name: SonarQube Scan  ## Scans code without running it for bugs
    #   uses: SonarSource/sonarcloud-github-action@v2
    #   with:
    #     args: >
    #       -Dsonar.organization=${{ secrets.SONAR_ORG }}
    #       -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  # 3. BUILD STAGE
  build:
    runs-on: ubuntu-latest
    needs: security

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t olaranmmy/devops-app:latest .

    - name: Save Docker image
      run: docker save olaranmmy/devops-app:latest -o image.tar

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar

  # 4. DAST STAGE
  dast:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download image ## since image is not transfeered across jobs
      uses: actions/download-artifact@v4
      with:
        name: docker-image


    - name: Load Docker image
      run: docker load -i image.tar


    - name: Run container
      run: docker run -d -p 3000:3000 olaranmmy/devops-app:latest

    - name: wait for app
      run: sleep 10

    # - name: DAST Scan (Dynamic Security Test, test for running app)
    #   run: |
    #     docker run --network="host" owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000

  # 5. PUSH STAGE
  push:
    runs-on: ubuntu-latest
    needs: dast

    steps:
    - uses: actions/checkout@v4

    - name: Download image
      uses: actions/download-artifact@v4
      with:
        name: docker-image


    - name: Load Docker image
      run: docker load -i image.tar


    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Image to DockerHub
      run: docker push olaranmmy/devops-app:latest